In [1]:
import numpy as np

In [18]:
def det_1(A):
    n = len(A[0, :])
    if n == 1:
        return A[0, 0]
    if n == 2:
        return A[0, 0] * A[1, 1] - A[1, 0] * A[0, 1]
    result = 0
    for i in range(n):
        if i == 0:
            result += A[0, 0] * det_1(A[1:, 1:])
        if i == n - 1:
            result += A[0, n-1] * det_1(A[1:, :(n-1)])
        else:
            B = np.hstack((A[1:, :i], A[1:, (i+1):]))
            result += A[0, i] * det_1(B)
        
    
    

In [12]:
B = np.arange(1, 26).reshape(5, 5).T
print(B)
print(B[1, 2])
print(B[:, 1:])

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
12
[[ 6 11 16 21]
 [ 7 12 17 22]
 [ 8 13 18 23]
 [ 9 14 19 24]
 [10 15 20 25]]


In [19]:
print(det_1(B))

TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

In [21]:
print(np.eye(4,6)[[0, 3], 
                  [1, 3]])

[0. 1.]


In [23]:
e = np.ones((10, 10))
print(e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
